[package]
name = "dcon"
version = "0.1.0"
edition = "2024"
authors = ["Angel Eckardt <eckardt.angel7@outlook.com>"]
license = "AGPL-3.0-only"                                # disallow competitors until launch
homepage = "https://github.com/aeckar/draft"
repository = "https://github.com/aeckar/draft"

[dependencies]
thiserror = "2.0.18"
taped = "1.5.2"
regex = "1.12.3"
unindent = "0.2.4"
derive_more = { version = "2.1.1", features = ["from", "deref", "display"] }
strum = { version = "0.28.0", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"], optional = true }

# provides `NotNan`, which enables `Eq`, `Ord`, and `Hash` for number encoding
ordered-float = "5.3.0"

[lib]
path = "src/lib.rs"

[features]
default = ["full"]
full = ["macros", "serde"]
macros = []
serde = ["dep:serde"]
